version: '3.8'

services:
  postgres-db:
    image: postgres:18
    container_name: centro_dia_db
    restart: always
    environment:
      POSTGRES_DB: centro_dia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

volumes:
  db_data: