spring.application.name=app
server.port=5555


spring.datasource.url=jdbc:postgresql://localhost:5434/centro_dia_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Iniciacion de configuracion
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:bbdd/schema.sql
# spring.sql.init.data-locations=classpath:bbdd/insert_admin.sql

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=schema_template

# OpenAPI
# springdoc.swagger-ui.path=/docs

# JWT Configuration
jwt.secret=c2VjdXJlLWp3dC1zZWNyZXQta2V5LWZvci1nZXN0aW9uLWFwcGxpY2F0aW9uLTIwMjQ=
jwt.expiration=86400000
